version: '3.5'

services:
    # Reverse proxy for SSL certificates
    nginx_proxy:
        image: jwilder/nginx-proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./proxy/config/proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
            - ./certificates/${HTTP_HOST}.pem:/etc/nginx/certs/${HTTP_HOST}.crt:ro
            - ./certificates/${HTTP_HOST}.key:/etc/nginx/certs/${HTTP_HOST}.key:ro
        restart: "no"

    nginx:
        image: nginx:latest
        environment:
            - VIRTUAL_HOST=${HTTP_HOST}
        volumes:
            - ../public:/var/www/html/public
            - ./nginx/config/vhost.nginx:/etc/nginx/conf.d/default.conf:ro
        restart: "no"

    php:
        build:
            context: .
            dockerfile: ./php/Dockerfile
            args:
                # It's UID in order to have the same rights on your computer and your docker container
                UID: "${DOCKER_UID}"
                TZ: "${TZ}"
        env_file:
            - .env
        environment:
            - APP_ENV=dev
        volumes:
            - ..:/var/www/html
        restart: "no"
